FROM flyway/flyway:7.15.0-alpine

ENV FLYWAY_URL=jdbc:postgresql://db:5432/onofre_store
ENV FLYWAY_USER=postgres
ENV FLYWAY_PASSWORD=23onofre.,
ENV FLYWAY_LOCATIONS=classpath:/db/migration

CMD ["migrate"]
