FROM flyway/flyway:7.15.0-alpine

ENV FLYWAY_URL=jdbc:postgresql://db:5432/onofre_store
ENV FLYWAY_USER=${DB_USERNAME}
ENV FLYWAY_PASSWORD=${DB_PASSWORD}
ENV FLYWAY_LOCATIONS=classpath:db/migration,classpath:db/testdata

CMD ["migrate"]
