version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  redis:
    image: redis
    ports:
      - "6379:6379"