DROP SEQUENCE if EXISTS SQ_CUSTOMER;

CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS TBL_CLIENTE;

CREATE TABLE TBL_CLIENTE(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_AGE VARCHAR(3) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
PRIMARY KEY(ID)
);