CREATE DATABASE ONOFRE_STORE;

CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_CUSTOMER(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_AGE VARCHAR(3) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE SEQUENCE SQ_REQUEST START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_REQUEST(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
REQUEST_DATE TIMESTAMP NOT NULL,
TOTAL BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES TBL_CUSTOMER(ID)
);

CREATE SEQUENCE SQ_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_PRODUCT(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
PRODUCT_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(3) NOT NULL,
UNIT_VALUE BIGINT NOT NULLL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);

REATE SEQUENCE SQ_REQUEST_ITEM START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_REQUEST_ITEM(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
QUANTITY BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(REQUEST_ID) REFERENCES TBL_REQUEST(ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES TBL_PRODUCT(ID)
);