CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_CLIENTE(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_AGE VARCHAR(3) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);