CREATE SEQUENCE SQ_ORDER START 1;

CREATE TABLE TBL_ORDER
(
    ID BIGINT NOT NULL DEFAULT NEXTVAL('SQ_ORDER'),
    STATUS    VARCHAR(255)   NOT NULL,
    TOTAL     NUMERIC(19, 2) NOT NULL,
    USER_ID   BIGINT         NOT NULL,
    UUID      VARCHAR(36)    NOT NULL,
    INC_DATE  TIMESTAMP      NOT NULL,
    MODF_DATE TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER (ID)
);


