CREATE TABLE TBL_CUSTOMER
(
    ID            BIGINT       NOT NULL,
    CPF           VARCHAR(255),
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_AGE  VARCHAR(3)   NOT NULL,
    UUID          VARCHAR(36)  NOT NULL,
    INC_DATE      TIMESTAMP    NOT NULL,
    MODF_DATE     TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SQ_CUSTOMER START 1;
