CREATE TABLE TBL_EMPLOYEE
(
    ID        BIGINT       NOT NULL,
    NAME      VARCHAR(100) NOT NULL,
    EMAIL     VARCHAR(100) NOT NULL,
    CPF       VARCHAR(255) NOT NULL,
    UUID      VARCHAR(36)  NOT NULL,
    INC_DATE  TIMESTAMP    NOT NULL,
    MODF_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SQ_EMPLOYEE START 1;
