CREATE TABLE TBL_PRODUCT
(
    ID           BIGINT         NOT NULL,
    PRODUCT_NAME VARCHAR(100)   NOT NULL,
    DESCRIPTION  VARCHAR(150)   NOT NULL,
    UNIT_VALUE   NUMERIC(19, 2) NOT NULL,
    UUID         VARCHAR(36)    NOT NULL,
    INC_DATE     TIMESTAMP      NOT NULL,
    MODF_DATE    TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SQ_PRODUCT START 1;
