CREATE SEQUENCE IF NOT EXISTS SQ_USER START 1;

CREATE TABLE TBL_USER
(
    ID            BIGINT       NOT NULL DEFAULT NEXTVAL('SQ_USER'),
    EMAIL         VARCHAR(100) NOT NULL,
    USUARIO       VARCHAR(16)  NOT NULL,
    CPF           VARCHAR(16)  NOT NULL,
    AGE           VARCHAR(3)   NOT NULL,
    NOME_COMPLETO VARCHAR(120) NOT NULL,
    SENHA         VARCHAR(100) NOT NULL,
    UUID          VARCHAR(36)  NOT NULL,
    INC_DATE      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODF_DATE     TIMESTAMP,
    PRIMARY KEY (ID)
);

