CREATE SEQUENCE IF NOT EXISTS SQ_USER START 1;

CREATE TABLE TBL_USER
(
    ID            BIGINT       NOT NULL DEFAULT NEXTVAL('SQ_USER'),
    EMAIL         VARCHAR(255) NOT NULL,
    USUARIO       VARCHAR(255) NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    SENHA         VARCHAR(255) NOT NULL,
    UUID          VARCHAR(36)  NOT NULL,
    INC_DATE      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODF_DATE     TIMESTAMP,
    PRIMARY KEY (ID)
);

