CREATE SEQUENCE IF NOT EXISTS SQ_ROLE START 1;

CREATE TABLE TBL_ROLE
(
    ID        BIGINT       NOT NULL DEFAULT NEXTVAL('SQ_ROLE'),
    PROFILE   VARCHAR(255) NOT NULL,
    UUID      VARCHAR(36)  NOT NULL,
    INC_DATE  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODF_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

