DO
$$
BEGIN
  IF NOT EXISTS (SELECT * FROM TBL_ROLE WHERE PROFILE = 'ADMIN') THEN
    INSERT INTO TBL_ROLE (ID, PROFILE, UUID, INC_DATE)
      VALUES (NEXTVAL('SQ_ROLE'), 'ADMIN', '45170d36-b4a8-4e19-85dc-ec5bea0ef3f9', CURRENT_TIMESTAMP);
END IF;
END $$;